__cli: SaltGenResource.py
__role: minion
acceptance_wait_time: 10
acceptance_wait_time_max: 0
always_verify_signature: false
append_minionid_config_dirs: []
auth_safemode: false
auth_timeout: 5
auth_tries: 7
auto_accept: true
autoload_dynamic_modules: true
autosign_timeout: 120
backup_mode: ''
beacons: {}
beacons_before_connect: false
cache: localfs
cache_jobs: false
cache_sreqs: true
cachedir: /home/amendlik/develop/salt-gen-resource-py2/var/cache/salt/minion
caller_floscript: /home/amendlik/source/salt/salt/daemons/flo/caller.flo
clean_dynamic_modules: true
cluster_masters: []
cluster_mode: false
cmd_safe: true
cython_enable: false
decrypt_pillar: []
decrypt_pillar_default: gpg
decrypt_pillar_delimiter: ':'
decrypt_pillar_renderers: [gpg]
default_include: minion.d/*.conf
default_top: base
disable_modules: []
disable_returners: []
enable_zip_modules: false
engines: []
env_order: []
environment: null
event_match_type: startswith
ext_job_cache: ''
extension_modules: /home/amendlik/develop/salt-gen-resource-py2/var/cache/salt/minion/extmods
extmod_blacklist: {}
extmod_whitelist: {}
failhard: false
file_buffer_size: 262144
file_client: remote
file_ignore_glob: []
file_ignore_regex: []
file_recv: false
file_recv_max_size: 100
file_roots:
  base: [/srv/salt, /srv/spm/salt]
fileserver_backend: [roots]
fileserver_followsymlinks: true
fileserver_ignoresymlinks: false
fileserver_limit_traversal: false
git_pillar_base: master
git_pillar_branch: master
git_pillar_env: ''
git_pillar_global_lock: true
git_pillar_includes: true
git_pillar_insecure_auth: false
git_pillar_passphrase: ''
git_pillar_password: ''
git_pillar_privkey: ''
git_pillar_pubkey: ''
git_pillar_refspecs: &id001 ['+refs/heads/*:refs/remotes/origin/*', '+refs/tags/*:refs/tags/*']
git_pillar_root: ''
git_pillar_ssl_verify: true
git_pillar_user: ''
gitfs_base: master
gitfs_env_blacklist: []
gitfs_env_whitelist: []
gitfs_global_lock: true
gitfs_insecure_auth: false
gitfs_mountpoint: ''
gitfs_passphrase: ''
gitfs_password: ''
gitfs_privkey: ''
gitfs_pubkey: ''
gitfs_refspecs: *id001
gitfs_remotes: []
gitfs_root: ''
gitfs_saltenv: []
gitfs_ssl_verify: true
gitfs_user: ''
grains: {}
grains_cache: false
grains_cache_expiration: 300
grains_deep_merge: false
grains_dirs: []
grains_refresh_every: 0
hash_type: sha256
http_max_body: 107374182400
http_request_timeout: 3600.0
id: saltdev
interface: 0.0.0.0
ioflo_console_logdir: ''
ioflo_period: 0.1
ioflo_realtime: true
ioflo_verbose: 0
ipc_mode: ipc
ipc_write_buffer: 0
ipv6: null
keysize: 2048
log_datefmt: '%H:%M:%S'
log_datefmt_console: '%H:%M:%S'
log_datefmt_logfile: '%Y-%m-%d %H:%M:%S'
log_file: /home/amendlik/develop/salt-gen-resource-py2/var/log/salt/minion
log_fmt_console: '[%(levelname)-8s] %(message)s'
log_fmt_logfile: '%(asctime)s,%(msecs)03d [%(name)-17s][%(levelname)-8s][%(process)d] %(message)s'
log_granular_levels: {}
log_level: debug
log_level_logfile: warning
log_rotate_backup_count: 0
log_rotate_max_bytes: 0
loop_interval: 1
master: localhost
master_alive_interval: 0
master_failback: false
master_failback_interval: 0
master_finger: ''
master_port: 4506
master_shuffle: false
master_sign_key_name: master_sign
master_tries: 1
master_type: str
master_uri_format: default
max_event_size: 1048576
mine_enabled: true
mine_functions:
  grains.items: []
mine_interval: 1
mine_return_job: false
minion_floscript: /home/amendlik/source/salt/salt/daemons/flo/minion.flo
minion_id_caching: true
minion_jid_queue_hwm: 100
minion_restart_command: []
minion_sign_messages: false
module_dirs: []
modules_max_memory: -1
multifunc_ordered: false
multiprocessing: true
on_demand_ext_pillar: [libvirt, virtkey]
open_mode: false
outputter_dirs: []
password: null
permissive_pki_access: false
pidfile: /home/amendlik/develop/salt-gen-resource-py2/var/run/salt-minion.pid
pillar_cache: false
pillar_cache_backend: disk
pillar_cache_ttl: 3600
pillar_opts: false
pillar_roots:
  base: [/srv/pillar, /srv/spm/pillar]
pillarenv: null
pillarenv_from_saltenv: false
ping_interval: 0
pki_dir: /home/amendlik/develop/salt-gen-resource-py2/etc/salt/pki/minion
providers: {}
proxy_host: ''
proxy_password: ''
proxy_port: 0
proxy_username: ''
pub_ret: true
publisher_acl: {}
publisher_acl_blacklist: {}
raet_alt_port: 4511
raet_clear_remote_masters: true
raet_clear_remotes: true
raet_lane_bufcnt: 100
raet_main: false
raet_mutable: false
raet_port: 4510
raet_road_bufcnt: 2
random_master: false
random_reauth_delay: 10
random_startup_delay: 0
range_server: range:80
reactor_refresh_interval: 60
reactor_worker_hwm: 10000
reactor_worker_threads: 10
recon_default: 1000
recon_max: 10000
recon_randomize: true
rejected_retry: false
render_dirs: []
renderer: yaml_jinja
renderer_blacklist: []
renderer_whitelist: []
resolve_dns_fallback: true
restart_on_error: false
retry_dns: 30
return_retry_timer: 5
return_retry_timer_max: 10
returner_dirs: []
root_dir: /home/amendlik/develop/salt-gen-resource-py2
salt_cp_chunk_size: 65536
schedule:
  __mine_interval: {enabled: true, function: mine.update, jid_include: true, maxrunning: 2,
    minutes: 1, return_job: false}
scheduler_before_connect: false
selected_target_option: glob
sign_pub_messages: false
sls_list: []
snapper_states: false
snapper_states_config: root
sock_dir: /home/amendlik/develop/salt-gen-resource-py2/var/run/salt/minion
sock_pool_size: 1
ssl: null
startup_states: ''
state_aggregate: false
state_auto_order: true
state_events: false
state_output: full
state_output_diff: false
state_top: top.sls
state_top_saltenv: null
state_verbose: true
states_dirs: []
sudo_user: ''
syndic_finger: ''
tcp_authentication_retries: 5
tcp_keepalive: true
tcp_keepalive_cnt: -1
tcp_keepalive_idle: 300
tcp_keepalive_intvl: -1
tcp_pub_port: 4510
tcp_pull_port: 4511
test: false
tgt: '*'
thorium_interval: 0.5
thorium_roots:
  base: [/srv/thorium]
top_file: ''
top_file_merging_strategy: merge
transport: zeromq
update_restart_services: []
update_url: false
use_master_when_local: false
user: amendlik
username: null
utils_dirs: [/var/cache/salt/minion/extmods/utils]
verify_env: true
verify_master_pubkey_sign: false
whitelist_modules: []
winrepo_branch: master
winrepo_cache_expire_max: 21600
winrepo_cache_expire_min: 0
winrepo_cachefile: winrepo.p
winrepo_dir: /srv/salt/win/repo
winrepo_dir_ng: /srv/salt/win/repo-ng
winrepo_insecure_auth: false
winrepo_passphrase: ''
winrepo_password: ''
winrepo_privkey: ''
winrepo_pubkey: ''
winrepo_refspecs: *id001
winrepo_remotes: ['https://github.com/saltstack/salt-winrepo.git']
winrepo_remotes_ng: ['https://github.com/saltstack/salt-winrepo-ng.git']
winrepo_source_dir: salt://win/repo-ng/
winrepo_ssl_verify: true
winrepo_user: ''
zmq_filtering: false
zmq_monitor: false
